# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Generate Dict

on:
  schedule:
    - cron: '0 0 ? ? 5'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - run: npm ci
    - run: npm run build
    - name: 'Upload Dict'
      uses: actions/upload-artifact@v4
      with:
        name: pcr-dict
        path: ./pcr-dict.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: '- 每周自动更新'
        name: 第 ${{ github.run_number }} 次自动更新
        tag_name: ${{ github.run_id }}
        files: ./pcr-dict.zip
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
